FROM python:3.7

RUN pip3 install mlflow>=1.0 \
    && pip3 install scipy \
    && pip3 install pandas \
    && pip3 install scikit-learn \
    && pip3 install cloudpickle \
    && pip3 install xgboost \
    && pip3 install matplotlib
